### ISSUE TITLE
Correlation detected where there is none

### ISSUE THREAD

**Issue by philastrophist** [swarnakumar/xicorpy#11]
**Describe the bug**
The following returns xi=0.25 where it should be 0.

```
import xicorpy
n = 10000
us = np.random.uniform(0, 1., n//2)
x, y = np.linspace(0, 1, n), np.append(np.zeros(n//2)+us, np.ones(n//2)-us)
y = np.where(y>0.5, 1, 0)

from numpy.lib.stride_tricks import sliding_window_view
window = 1000
sliding = sliding_window_view(y, window_shape=window).mean(axis=1)
plt.scatter(x, y)
plt.plot(x[window-1:], sliding, '-')
xicorpy.compute_xi_correlation(x, y)
```

![image](https://user-images.githubusercontent.com/14169057/235989390-9b55c594-1c92-45a9-8887-082af4ea11e8.png)

Change the unform 0,1 random number generator to a smaller range and the coefficient increases as expected but at pure random noise it remains at 0.25. If I make it a continuous variable by removing `y = np.where(y>0.5, 1, 0)` then it works as expected.

Any ideas?

Thanks

**Comment by swarnakumar** [comment]
By default, it computes modified Xi based on https://arxiv.org/abs/2108.06828

When I run this with `compute_xi_correlation(x, y, get_modified_xi=False)`, I get values very close to 0 - typically around 0.003

Let me investigate further why the modification is generating such a large value.

**Comment by swarnakumar** [comment]
I re-read Lin and Han's paper again. The code is correct. However:

1. The paper assumes X and Y are always continuous, and hence there are no ties. Chatterjee's original paper doesn't have this assumption
2. I ran simulations with the code you used above - but with increasing number of levels. As the number of levels increases, modified Xi comes down. For 2 levels, it's ~0.25, for 3 levels it's ~0.16, and so on. 
3. Based on the above two caveats, I am not sure if modified Xi is even applicable to categorical data with less number of levels.

Currently `get_modified_xi` defaults to `True` in the code. I intend to change that to `False`, and update documentation with the above caveats. I hope to close this over the weekend, and publish a new release.

Thanks for using the package, and pointing this out!

**Comment by philastrophist** [comment]
Thank you for looking into this. I guess it is up to the user to identify ties and change the method. Or maybe there could be a warning? 
As far as I understand, the modified method is an attempt to reduce the bad convergence rate n^-1/4 to n^-1/2, so I guess it should always be preferred unless there are a large number of ties.

**Comment by swarnakumar** [comment]
Updated code to warn in case of ties.
