### ISSUE TITLE
Negative correlation values returned

### ISSUE THREAD

**Issue by MikeB2019x** [swarnakumar/xicorpy#32]
when I run this code from [](https://swarnakumar.github.io/xicorpy/xi/)
```
import pandas as pd
import xicorpy

x = pd.DataFrame({
    "x_1": [10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5],
    "x_2": [10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5],
    "x_3": [10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5],
    "x_4": [8, 8, 8, 8, 8, 8, 8, 19, 8, 8, 8],
})
y = pd.DataFrame({
    "y_1": [8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68],
    "y_2": [9.14, 8.14, 8.74, 8.77, 9.26, 8.1, 6.13, 3.1, 9.13, 7.26, 4.74],
    "y_3": [7.46, 6.77, 12.74, 7.11, 7.81, 8.84, 6.08, 5.39, 8.15, 6.42, 5.73],
    "y_4": [6.58, 5.76, 7.71, 8.84, 8.47, 7.04, 5.25, 12.5, 5.56, 7.91, 6.89],
})

xi = xicorpy.compute_xi_correlation(x, y)
```
I get the following:
	y_1	y_2	y_3	y_4
x_1	0.513889	0.416667	0.736111	-0.138889
x_2	0.513889	0.416667	0.736111	-0.138889
x_3	0.513889	0.416667	0.736111	-0.138889
x_4	-0.083333	-0.152778	-0.097222	0.111111

I thought Xi returned only values between 0 and 1.  What are the negative values?

**Env:**
macOS Sonoma
Jupyter 6.5.6
pandas 2.2.2
xicorpy 0.5

**Comment by swarnakumar** [comment]
Firstly, apologies for the delay.

Second, Xi can sometimes return -ve values. From Page 4 of the paper:

```
the minimum possible value of ξn(X, Y ) is −1/2 + O(1/n), and the minimum is attained when the top n/2 values of Yi are placed alternately with the bottom n/2 values. This seems to be paradoxical, since Theorem 1.1 says that the limiting value is in [0, 1]. The resolution is that Theorem 1.1 only applies to i.i.d. samples. Therefore a large negative value of ξn has only one possible interpretation: the data does not resemble an i.i.d. sample.
```

In practice, the value of 𝜉 can be negative, but this negativity does not have any innate significance, other than "close to zero". This is because 𝜉 goes asymptomatically to 0 when there's no correlation
