### ISSUE TITLE
calculation of R_N(i)

### ISSUE THREAD

**Issue by sommera18** [swarnakumar/xicorpy#8]
https://github.com/swarnakumar/xicorpy/blob/d3a9eea4e5dda4b3a48fe9e339b61c4b2794526a/xicorpy/conditional_dependence.py#L216

Shouldn´t this be 
    `r_n = r_y[n_i] `
instead of 
    `r_n = ss.rankdata(n_i, method="max")`
(like the calculation of r_m)? Or what is the idea of taking ranks of the nearest neighbor indices?

Same in line 234. 

![image](https://user-images.githubusercontent.com/120200624/206748504-5805f5da-cbfd-4f0f-8e5a-ffba6b0e272d.png)
This is what the paper says.

Best regards

**Comment by swarnakumar** [comment]
R<sub>N(i)</sub> in the paper is rank of `N(i)`. And hence that computation.

Now, while R<sub>M(i)</sub> is also to be read in a similar fashion, its a much easier computation - that can be written directly as `r_y[m]`

**Comment by sommera18** [comment]
$R_{N(i)}$ is not the rank of N(i). It is the Rank of $y_{N(i)}$. R always denotes the rank of some y-value.

$R_i$ is the rank of $y_i$
$R_{N(i)}$ is the rank of the y-value with the index N(i). So if $N(i) = j$, then $R_{N(i)} = R_j$.
Analogous , $R_{M(i)}$ is the rank of $y_{M(i)}$.

**Comment by swarnakumar** [comment]
You maybe right. Would you want to submit a PR?

**Comment by sommera18** [comment]
Sure, but I cannot push a new branch. How can I push the changes?
