### ISSUE TITLE
foci stopping rule

### ISSUE THREAD

**Issue by sommera18** [swarnakumar/xicorpy#9]
https://github.com/swarnakumar/xicorpy/blob/d3a9eea4e5dda4b3a48fe9e339b61c4b2794526a/xicorpy/foci.py#L93-L106

The else-if-block from line 98 - 104 does not seem to be appropriate. The difference between `next_t` and `curr_t` is not a reasonable stopping criterion. `next_t` is the conditional dependence $\max_{j \notin \{ j_1, \ldots, j_k \}} T(y, x_j | x_{j_1}, \ldots, x_{j_k})$. As long as it is greater 0, $x_j$ (next_p) will be added to the selected features. When `next_t` is zero or less, that means that $x_j$ cannot contribute to the prediction of y, so that the algorithm stops. That is how the foci algorithm is described in the paper:
![image](https://user-images.githubusercontent.com/120200624/207175699-256d70e1-39d1-4de0-9d55-d9b9545366e5.png)
(page 8)

So I would suggest:
```python
while not stop and len(current_selection) < num_features:
    next_p, next_t = self._get_next_p(current_selection)

    if next_t <= 0 and auto_stop:  # pragma: no cover
        stop = True
    else:
        current_selection.append(next_p)
```

**Comment by swarnakumar** [comment]
Closed in PR #13
